### ISSUE TITLE
Incorrect Header on Business Case PDF/HTML

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [GSA/ITDB-schema#346]
In looking at the business case PDFs for other reasons, I noted that above the list of projects (and right below the "Section B1: Projects" section header) is the label "1. If the Investment/program uses an automated tool for requirements gathering, tracking, planning, or management, identify the automated tool."  This label does not appear to be from anywhere in the FY20 guidance, nor does it seem to accurately describe the table that follows - the list of projects.  I suspect this text comes from some earlier year's guidance and was missed during updates. 

Having noted that, the "Section B1: Projects" header is incorrect, and it appears that the section labels for projects and operational data have not been updated for FY20, with risks now being section B (instead of A) and projects and operational data shifting to C and D, respectively.  (There are also some other differences, like I am not sure the use of "II." to designate the detail section is used any longer.)

This appears to affect both the PDF and HTML versions and both the public and private versions of the Business Case PDFs.

This is a low priority issue for us as there was not a specific concern raised by users.

**Comment by rydougherty** [comment]
Hi Bill,

Thank you for reaching out. We have created a ticket for the Business Case PDF header and label issues. The ticket has been added to our backlog for Product Owner prioritization. Please let us know if you have any other questions regarding this issue.

Thanks,
Ryan

**Comment by rydougherty** [comment]
Hi Bill,

I wanted to follow up and inform you that we have deployed a fix for the Business Case PDF/HTML Headers issue. Please let us know if can close this issue.

Thanks,
Ryan

**Comment by bill-gehrke-hhs** [comment]
Thanks.  The issue appears to be resolved.

Bill
