### ISSUE TITLE
FY21 General Data Report - get Operation

### ISSUE THREAD

**Issue by courtneycorwin** [GSA/ITDB-schema#350]
Hi All,

I noticed that there's a structure validation indicating that the get operation is not available.  Is this because it's a new report or some sort of temporary error?

Thanks!
Courtney

**Comment by rydougherty** [comment]
Hi Courtney, thanks for reaching out. You are unlikely to ever encounter this error following the go-live of FY 2021. The IT Dashboard has controls that govern which operations are available at a given time. This validation is linked to these controls. However, the current plan is to leave the General Data Report open year round (unlike the IT Budget).
