### ISSUE TITLE
FY21 General Data Report - Activities

### ISSUE THREAD

**Issue by courtneycorwin** [GSA/ITDB-schema#354]
Since the activities in this report do not have an operation, does that mean if they're deactivated via the business case, they will be deactivated here as well?  Or will the list sent up always overwrite whatever list existed?

**Comment by rydougherty** [comment]
Hi Courtney,

Thanks for reaching out. The Deployment Report latches on to a given activity. Therefore, each "Activity" casing within the Deployment Report functions as an `update` operation, and there is no need for an `operation` tag at the activity level. A given activity cannot have more than one attached Deployment Report. 

Each time you submit an activity level Deployment Report the `releasesToTest` and `releasesToProd` data will overwrite based on whatever is in the submission file. The other data points will only be updated if they are included in the request file.

**Comment by courtneycorwin** [comment]
So, if an activity is deactivated via the Business Case, will it be removed from the deployment report, or will the report have to be resubmitted without the deactivated activity to remove it?

**Comment by rydougherty** [comment]
Hi Courtney, each deployment report is attached to given activity. So if you deactivate that activity, either through the Business Case or the SIR, the associated deployment report will also be deactivated.

**Comment by courtneycorwin** [comment]
That's what I thought.  Thanks for confirming!
