### ISSUE TITLE
Major Business Case Validation Submission Error

### ISSUE THREAD

**Issue by kengineer** [GSA/ITDB-schema#367]
I'm trying to submit a validation submission for a Major Business Case annual submission to the UAT environment and am receiving the following error:
```xml
<sr:message level="error" xpath="/operations[1]/investmentInformation[1]/annualSubmission[1]/updateInvestment[1]">000171-BSC: The submitted investment 429-000002500 must be active in the 2021 IT Portfolio and can only be Type of Investment '01' or '06'.</sr:message>
```
I'm assuming this means that this investment must first be submitted to the IT Budget endpoint in addition to having an investment type of 01 or 06. However, this investment has been submitted to the IT Budget and I have verified this with a "get" request to the IT Budget endpoint. I also verified that its investment type is indeed 01. 

![image](https://user-images.githubusercontent.com/233493/64046381-be6e8800-cb39-11e9-8cdc-c2165919f153.png)

Is there something else I'm missing?

Ken Nehring supporting NRC.

**Comment by mayuri-khatri** [comment]
Hi Ken,

Thank you for your question. There was an issue with the post process not firing. We have just run the IT Budget post process manually. Please try the Business Case submission one more time.

Thank you,
ITDB Support

**Comment by kengineer** [comment]
Works now. Thanks.
