### ISSUE TITLE
BY21 Systems Inventory - Functions

### ISSUE THREAD

**Issue by courtneycorwin** [GSA/ITDB-schema#368]
Hi All,

The guidance indicates that Functions are separate from Products.  However, the lastest xsd file indicates that they should be associated with Products.  Can you confirm what the intention is?

Thanks!
Courtney

**Comment by mayuri-khatri** [comment]
Hi Courtney,

Thank you for bringing this up. The GSA/ITDB-Schema repository has now been updated with the corrected Systems Inventory XSD.

Please let us know if you have any further questions.

Thank you,
ITDB Support
