### ISSUE TITLE
BY21 - Systems Inventory List - Format (High Priority)

### ISSUE THREAD

**Issue by courtneycorwin** [GSA/ITDB-schema#370]
Hi All,

I've been running some tests with the Systems Inventory List submission.  I've had to omit the date fields under the Product node since sending them up as blank resulted in a submission error. (I know we discussed that yesterday)

Based on the tests I've run, it looks like everything is going up using an "add" operation this year.  Is that correct?

**Comment by rydougherty** [comment]
Hi Courtney,

Could you elaborate more on what you mean by everything using an "add" operation? The Systems and Products will leverage "add" and "update" operations in the same manner as last year. Each System and Product will be associated with a given IT Dashboard generated OMB ID and/or an Agency generated ID. After an "add" operation, you can use those identifiers to update Systems and Products data. 

For your second question, could you email us the file that is failing? In general if you submit those date fields as follows, the IT Dashboard will accept the submission:

```
<lastMajorTechRefresh></lastMajorTechRefresh>
<anticipatedTechRefresh></anticipatedTechRefresh>
<productExpectEndOfLife></productExpectEndOfLife> 
```

Thanks,
Ryan

**Comment by courtneycorwin** [comment]
Hi Ryan,

For every investment I've tried submitting the SIL for, the response to the get operation is that the UII isn't there, so everything has been going up using an add operation.  I think this is fine if it's what's expected, but I can't tell since we can't submit Confirmation for our ITPS.

Regarding the dates, when I send up a tag like <productExpectEndOfLife/>, I get a submission error.  If I omit the tag altogether, I receive no error other than the UII hasn't been submitted as part of an ITPS yet.

Let me know if this needs further explanation.  Thanks!
Courtney

**Comment by mayuri-khatri** [comment]
Hi Courtney,

Thank you for providing these details. Could you please provide an example file including the UII and System ID combination(s) producing this issue?

Thank you,
ITDB Support

**Comment by courtneycorwin** [comment]
I've finally found an investment where the SIL goes up using an update operation, so I'm good there.  I'm still not getting an error when the anticipated refresh and product end of life dates are omitted, but I do get one if I include them as blank.

**Comment by samanthathomas20** [comment]
Hi Courtney,

We have successfully deployed a fix for this issue. 

Please let us know if you have any issues.

Thanks,
Sam
ITDB Support

**Comment by courtneycorwin** [comment]
Thanks for letting me know!  I'll test it tonight and let you know how it goes.

**Comment by samanthathomas20** [comment]
Also, you will need to resubmit your AITPS. 

Please let us know if you run into any issues.

Thanks,
Sam
ITDB Support

**Comment by courtneycorwin** [comment]
I still don't get an error message if I omit the date tags, but I don't get one if I send them up blank either, so I've marked them required in the map file for my agencies.  However, sometimes my agencies customize their map files, so it's possible they will mark these elements as optional.  I'm going to close this ticket, I just wanted to make you aware.
