### ISSUE TITLE
Adding a new project linked to an existing metric

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [GSA/ITDB-schema#373]
In the 2021 UAT environment, I am attempting to add projects, both to an existing investment and to a new investment (using the monthly submission option.)  In both cases, if I attempt to link the new project to an existing metric, I receive the following error:

Project with agency identifier '123456': 000607-BCD: All new projects must provide a complete set of projectMetric data

This seems to occur whether the metric is new or existing and only during an add.  (If I copy the same XML to an existing project, it is accepted.)  Could you explain what is expected with this error?  Just because a project is new should not mean it requires a new metric.

**Comment by mayuri-khatri** [comment]
Hi Bill,

You should be able to link new projects with existing metrics. Could you please send us the request file you are submitting which is causing the 000607-BCD error?

Thank you,
ITDB Support
