### ISSUE TITLE
Deployment Report Not Recognizing Project Id

### ISSUE THREAD

**Issue by kengineer** [GSA/ITDB-schema#387]
Two question here. The first is since this is the first year for the deployment report, are all submissions supposed to use the "add" operation or do we use the "update" operation since the investments do exist in the ITDB via other end points?

My second question is when I submit the XML below as either an add or and update, I get the error **000001-DEP: projectActivityID 17307 is not valid for UII  429-000002600**. I know for sure that the project does exist under the investment. Am I not submitting the correct ID for that field? The ID 17307 is the ID the ITDB dashboard created and returned when the project was originally added in the business case endpoint. The ID 120549 is the activity ID returned by the ITDB when the activity was created.

```xml
<generalDataReports xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" validateOnlyIndicator="true">
	<deploymentReport>
		<operation>update</operation>
		<details>
			<UII>429-000002600</UII>
		</details>
		<Activities>
			<Activity>
				<projectActivityID xsi:type="xsd:string">17307</projectActivityID> <!-- ITDB API Generated Project ID -->
				<activityID xsi:type="xsd:string">120549</activityID> <!-- ITDB API Generated Activity ID -->
				<agencyActivityID xsi:type="xsd:string">368</agencyActivityID>
				<agencyProjectActivityID xsi:type="xsd:string">1816</agencyProjectActivityID>
				<multipleReleases>no</multipleReleases>
				<userEngagement>1</userEngagement>
				<releaseReview>N/A</releaseReview>
			</Activity>
		</Activities>
	</deploymentReport>
</generalDataReports>
```
Thanks,

Ken Nehring supporting NRC

**Comment by samanthathomas20** [comment]
Hi Ken

Agencies can use both "add" and "update" operations for the Deployment Report.

The reason you are receiving the error is because of the multiple activity identifiers being submitted. Please drop the activityID and agencyActivityID, leaving projectActivityID and/or agencyProjectActivityID (you really only need to provide one unique identifier).

Please let us know if you have any further questions.

Thanks,
Sam
ITDB Support

**Comment by kengineer** [comment]
I tried submitting the below and also a version without the agencyProjectActivityID and neither worked. I still get the response **000001-DEP: projectActivityID 17307 is not valid for UII  429-000002600**. I also tried just submitting agencyProjectActivityID on its own and the response was **000001-DEP: projectActivityID  is not valid for UII  429-000002600**. So it looks like it at least wants projectActivityID.

```xml
<generalDataReports xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" validateOnlyIndicator="true">
	<deploymentReport>
		<operation>update</operation>
		<details>
			<UII>429-000002600</UII>
		</details>
		<Activities>
			<Activity>
				<projectActivityID xsi:type="xsd:string">17307</projectActivityID>				
				<agencyProjectActivityID xsi:type="xsd:string">1816</agencyProjectActivityID>
				<multipleReleases>no</multipleReleases>
				<userEngagement>1</userEngagement>
				<releaseReview>N/A</releaseReview>
			</Activity>
		</Activities>
	</deploymentReport>
</generalDataReports>
```

**Comment by kengineer** [comment]
Anyone have a chance to look at this yet? We're experiencing this for all investments we've tried so far.

**Comment by mayuri-khatri** [comment]
Hi Ken,

The ID values you are providing seem to be Projects level data. Please ensure the projectActivityID and agencyProjectActivityID represent your Activity IDs and not Project IDs.

Let us know if you have any additional questions or continue to encounter this issue.

Thank you,
Mayuri
ITDB Support

**Comment by kengineer** [comment]
You are right. Thank you.
