### ISSUE TITLE
Deployment Report Failing to Insert or Update

### ISSUE THREAD

**Issue by kengineer** [GSA/ITDB-schema#391]
When submitting the following XML, I get a successful response for a validation submission but get the error message **000617-DEP: ERROR: Insert or Update failed**. It's listed twice, presumably for each activity. Is there something wrong with the submission or is something wrong on the API side? Note I've tried both an add and update operation and both pass validation.

```xml
<generalDataReports xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" validateOnlyIndicator="false">
	<deploymentReport>
		<operation>add</operation>
		<details>
			<UII>429-000009200</UII>
		</details>
		<Activities>
			<Activity>
				<projectActivityID xsi:type="xsd:string">120580</projectActivityID>
				<agencyProjectActivityID xsi:type="xsd:string">365</agencyProjectActivityID>
				<multipleReleases>no</multipleReleases>
				<userEngagement xsi:type="xsd:string">1</userEngagement>
				<releaseReview>NA</releaseReview>
			</Activity>
			<Activity>
				<projectActivityID xsi:type="xsd:string">120581</projectActivityID>
				<agencyProjectActivityID xsi:type="xsd:string">366</agencyProjectActivityID>
				<multipleReleases>no</multipleReleases>
				<userEngagement xsi:type="xsd:string">1</userEngagement>
				<releaseReview>NA</releaseReview>
			</Activity>
		</Activities>
	</deploymentReport>	
</generalDataReports>
```
I apologize in advanced if you covered this on today's call; I wasn't able to join until near the end.

Thanks,
Ken Nehring supporting NRC

**Comment by rydougherty** [comment]
Hi Ken,

We have just deployed a fix for this issue. Can you please try submitting again?

Thanks,
Ryan

**Comment by kengineer** [comment]
It's working now. Thanks!
