### ISSUE TITLE
"Virus signature found in submission" response

### ISSUE THREAD

**Issue by kengineer** [GSA/ITDB-schema#417]
I was testing something in the UAT environment (myuat-2021) and sent a request like the one below. Surprisingly the response I received back was "Virus signature found in submission. The submitted file has been deleted." I tried other submissions in other environments and received the same response. I even submitted a validation request to the production ITDB endpoint (myit-2021) and received the same virus error message.

Can you verify the endpoints are working as expected?

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<operations xmlns="http://www.itdashboard.gov/service"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.itdashboard.gov/service ../Exchange/serviceRequest.xsd">
  <investmentInformation uniqueInvestmentIdentifier="429-000002500">
    <getInformation>
      <getInvestment id="String"/>      
    </getInformation>
  </investmentInformation>
</operations>
```

Thanks,
Ken Nehring 
Supporting NRC

**Comment by mayuri-khatri** [comment]
Hi Ken,

Thank you for bringing this to our attention. We have added a ticket to investigate this issue and will follow up when we have additional details.

Regards,
Mayuri
ITDB Support

**Comment by samanthathomas20** [comment]
Hi Ken,

Can you attempt your submission again? Our infrastructure provider has informed our team that the reported virus scan issue should now be resolved. 

If you are still encountering issues, please let us know.

Thanks,
Sam
ITDB Support

**Comment by kengineer** [comment]
It works now.
