### ISSUE TITLE
CIO Authority records should be a unique combination of Year, Budget Account, and Agency

### ISSUE THREAD

**Issue by lschwenkebah** [GSA/ITDB-schema#447]
Currently, CIO Authority submissions are limited to 1 per Agency. Instead, Agencies should be able to submit multiple CIO Authority records, where each record is a unique combination of Year, Budget Account, and Agency.

**Comment by rydougherty** [comment]
Item Status: Set for deployment this week (7/12 - 7/16)

**Comment by rydougherty** [comment]
We have deployed a fix for this issue. Each CIO Authority record should be associated with a unique combination of Year, Budget Account, and Agency.
