### ISSUE TITLE
All boolean submission fields in IT Collect should only accept "true" or "false"

### ISSUE THREAD

**Issue by lschwenkebah** [GSA/ITDB-schema#448]
Currently, submitting false for incrementalDevelopment and/or softwareProject results in a constraint violation when it shouldn't. We need to ensure all boolean fields in IT Collect only accept 'true' or 'false'. We should disallow submission of 'True' 'TRUE' 'False' 'FALSE'

**Comment by rydougherty** [comment]
Item Status: Set for deployment this week (7/12 - 7/16)

**Comment by rydougherty** [comment]
We have deployed a fix for this item. Vendors should send over all boolean values as either `true` or `false`. More information can be found on the [ReDoc API Schema](https://gsa.github.io/ITDB-schema/).
