### ISSUE TITLE
[ITC Collect] Creates a Services resource. "{{baseUrl}}/v1/services" POST is not working with default PayLoad in Postman

### ISSUE THREAD

**Issue by KellyHarrisT** [GSA/ITDB-schema#453]
Testing of Post of endpoint /v1/services produces "Extra attributes not allowed" (See Below)
Payload:
{
  "currentUii": "018-000000123",
  "agency": "018",
  "title": "IT Collect Development",
  "description": "Sample description of the IT Dashboard modernization process.",
  "changeInStatus": "11",
  "changeInStatusDescription": "New Service",
  "previousUII": "018-000001234",
  "sharedServiceCode": "00",
  "sharedServiceId": "0024",
  "missionSupportCategory": [
    "01"
  ],
  "bureauCode": "00",
  "partOfAITPS": "01",
  "standardIdCategory": "01",
  "missionSupportArea": "00",
  "investmentType": "01",
  "returnOnInvestment": "Sample description of a return on an investment.",
  "nssId": "01",
  "publicUrls": [
    "https://example.gov"
  ],
  "isRetired": false,
  "rebaseLineId": "",
  "agencyId": "string"
}
Results in:
{
    "@context": "/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "ExtraAttributesException",
    "hydra:description": "Extra attributes are not allowed (\"currentUii\", \"missionSupportCategory\" are unknown)."
}

**Comment by rydougherty** [comment]
Hi Kelly,

Thanks for reaching out. Please make the following changes in your submission file:

`"currentUii": "018-000000123"` -> `"currentUII": "018-000000123"`
`"missionSupportCategory": ["01"] `-> `"missionSupportCategories": ["01"] `

**Comment by KellyHarrisT** [comment]
Hello,

Thank You for your response.
I made the changes, now it gives me a 403.

Kelly

**Comment by rydougherty** [comment]
Hi Kelly - thanks for following up. The agency code and current uii values (018) in your submission file are associated with the Department of Education. Since your client id and credentials are associated with Treasury, you should use Treasury's (015) code:

- agency: 015
- currentUII: 015-[Insert Unique Investment Identifier Here]

**Comment by KellyHarrisT** [comment]
Thanks!
