### ISSUE TITLE
[IT Collect] - Retrieving a particular service

### ISSUE THREAD

**Issue by KellyHarrisT** [GSA/ITDB-schema#454]
I have been testing functionality.
I was able to add a service, now I want to retrieve that service.
Using Postman, I am using Get {{baseUrl}}/v1/services/:id.  What should be the ID from the following to retrieve the one item.

GET Services ({{baseUrl}}/v1/services?page=1)
{
    "@context": "/contexts/Services",
    "@id": "/v1/services",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/v1/services/string",
            "@type": "Services",
            "created": "2021-08-05 19:41:26",
            "lastModified": "2021-08-05 19:41:26",
            "createdBy": "kelly.harris2@treasury.gov",
            "updatedBy": "kelly.harris2@treasury.gov",
            "agencyCode": null,
            "agencyId": "string",
            "currentUII": "015-000000123",
            "agency": "015",
            "title": "IT Collect Development",
            "description": "Sample description of the IT Dashboard modernization process.",
            "changeInStatus": "11",
            "changeInStatusDescription": "New Service",
            "previousUII": "",
            "sharedServiceCode": "00",
            "sharedServiceId": "0024",
            "missionSupportCategories": [
                "01"
            ],
            "bureauCode": "00",
            "partOfAITPS": "01",
            "standardIdCategory": "01",
            "missionSupportArea": "00",
            "investmentType": "01",
            "returnOnInvestment": "Sample description of a return on an investment.",
            "nssId": "01",
            "publicUrls": [
                "https://example.gov"
            ],
            "isMasked": false,
            "isRetired": false,
            "timePeriodId": "TimePeriod20223",
            "createdTimePeriod": "TimePeriod20223",
            "retiredTimePeriod": null,
            "rebaseLines": [
                ""
            ]
        }
    ],
    "hydra:totalItems": 1,
    "hydra:pageCount": 1,
    "hydra:perPage": 200,
    "hydra:currentPage": 1,
    "hydra:firstPage": 1,
    "hydra:lastPage": 1,
    "hydra:nextPage": 1
}

**Comment by KellyHarrisT** [comment]
I figured out the answer.  For this example I should sent in the id as "string"  ("agencyId": "string"),

I will likely delete this item, since it is wrong.

**Comment by rydougherty** [comment]
Hi Kelly,

Yes, you are correct that you should your agency identifier within the path parameters. I will go ahead and close out the item.

Thanks,
Ryan
