### ISSUE TITLE
[IT Collect] Receiving 403 - Please explain

### ISSUE THREAD

**Issue by KellyHarrisT** [GSA/ITDB-schema#458]
Posting a Service
Request: {"agencyId": "015000200116","currentUII": "015-000200116","agency": "005","title": "1 Enterprise Architecture IPT","description": "Test.","changeInStatus": "01", "changeInStatusDescription": "New","sharedServiceCode": "48","bureauCode": "00","partOfAITPS": "01","standardIdCategory": "01","investmentType": "01","nssId": "01","isRetired": false}

Response: {"@context":"\/contexts\/Error","@type":"hydra:Error","hydra:title":"HttpException","hydra:description":"Access to this record is forbidden","hydra:request_id":"28daef21-bdce-96d3-b48f-34791734baac"}

**Comment by rydougherty** [comment]
Hi Kelly,

Thanks for reaching out. To further investigate on our end, can you please email the access token that you using to itdb-support@gsa.gov?

Thanks,
Ryan

**Comment by rydougherty** [comment]
Resolved over email
